### ISSUE TITLE
Retries for mutations

### ISSUE THREAD

**Issue by nealyip** [awslabs/aws-mobile-appsync-sdk-js#372]
The appsync js sdk keeps retrying for mutations even if 401 has been thrown.

![retries](https://user-images.githubusercontent.com/6487585/54579815-3fc8d700-4a40-11e9-852e-7bff0f141788.jpg)

Here is a snippet of my code
```
const args: AWSAppSyncClientOptions = {
            url: this.configService.config.graphqlEndpoint,
            region: this.configService.config.region,
            auth: {
                type: this.configService.config.authenticationType,
                jwtToken: async () => await this.authorize()
            }
        };
this.client = new AWSAppSyncClient(args);
this.client.hydrated().then(async (client: AWSAppSyncClient<any>) => {
      const result = await client.mutate(options);
      console.log(result);
});
```

How can I make no retries for 401 error?

Thanks

Dependencies 
"aws-appsync": "~1.7.2"

**Comment by manueliglesias** [comment]
@nealyip what's the actual version you have in your project? It might be different if you have a yarn.lock or packgae-lock.json

e.g.
```sh
yarn list | grep appsync
# or
npm list --pattern appsync
```

**Comment by nealyip** [comment]
> @nealyip what's the actual version you have in your project? It might be different if you have a yarn.lock or packgae-lock.json
> 
> e.g.
> 
> ```shell
> yarn list | grep appsync
> # or
> npm list --pattern appsync
> ```

Thanks for your reply.

Here attached the result

npm list --pattern aws-appsync
`-- aws-appsync@1.7.2

**Comment by fabrizioromanelli** [comment]
Same problem here with aws-appsync@1.8.0 (not posting the code as it's similar to @nealyip 's)

**Comment by manueliglesias** [comment]
This is interesting, I thought it was fixed in #308

Do you see the same behavior if you do ` disableOffline: true`:

```ts
const args: AWSAppSyncClientOptions = {
            url: this.configService.config.graphqlEndpoint,
            region: this.configService.config.region,
            auth: {
                type: this.configService.config.authenticationType,
                jwtToken: async () => await this.authorize()
            },
           disableOffline: true
        };
this.client = new AWSAppSyncClient(args);
```

**Comment by fabrizioromanelli** [comment]
@manueliglesias I've just tried with _disableOffline: true_ and it is working like a charm. First the time the error has been thrown, AppSync client stops trying for mutation (or query).

**Comment by fsproru** [comment]
Getting the same issue when the AppSync URL doesn't exist (i.e. domain not found). The mutation just keeps retrying infinitely. Is there a way to configure the number of retries?

**Comment by loongdefect** [comment]
Same issue when jwtToken expired. The mutation just keeps retrying infinitely.

**Comment by fsproru** [comment]
Hey @manueliglesias, hope all is well. Just following up here. The issue still exists in version 1.8.1 and 1.8.0. `disableOffline: true` also doesn't change the behavior. AppSync client keeps on retrying on an error coming from the server (in our case 504).

It would be fantastic if we can disable this retrying behavior so our app can be resilient to network errors.

Let us know if there is any way we can make it happen.

Thank you,
Alex

**Comment by dennis3001** [comment]
The issue still exists even in 3.0.3

**Comment by Joroze** [comment]
As @fsproru said, it would be great if we can disable this retrying behavior. This really needs to be addressed and fixed. Our company uses this library for AppSync (GraphQL) requests and we may be forced to find an alternative solution.

**Comment by nealyip** [comment]
It's already been a long time since I reported this problem. I solved this by switching to aws-amplify long time ago.

However, I keep seeing people encountering similar issues. That's why I made this repo hopefully helpful to the developers of this appsync sdk to address the issue more easily. I'm not sure if this's the exact cause of the issue that others here are encountering.

https://github.com/nealyip/nealyip-sample-appsync-infinite-retries

As a quick starter
```
npm i
npm run start
```

![Screenshot 2020-10-13 213340](https://user-images.githubusercontent.com/6487585/95867513-cd46e700-0d9b-11eb-8bdc-c9810b913cd2.png)

if a mock server returned 400, 401, 403, 404 etc, it stopped at the first response.
However, if it returned 500, 502, 503 etc, it looped infinitely. 

So it seems that the infinite retry issue 401 status code was addressed but if it's 5xx, we can't leave the loop and recover the error manually.

**Comment by nealyip** [comment]
It's already been a long time since I reported this problem. I solved this by switching to aws-amplify long time ago.

However, I keep seeing people encountering similar issues. That's why I made this repo hopefully helpful to the developers of this appsync sdk to address the issue more easily. I'm not sure if this's the exact cause of the issue that others here are encountering.

https://github.com/nealyip/nealyip-sample-appsync-infinite-retries

As a quick starter
```
npm i
npm run start
```
### For query operations,
![Screenshot 2020-10-13 222000](https://user-images.githubusercontent.com/6487585/95873211-447f7980-0da2-11eb-8b1c-61848200366c.png)

if a mock server returned 400, 401, 403, 404 etc, it would stop at the first response.
However, if it returned 500, 502, 503 etc, it would loop infinitely. 


### For mutation operations,
The above which happens on 5xx errors still happens on 4xx too

![Screenshot 2020-10-13 222141](https://user-images.githubusercontent.com/6487585/95873500-90cab980-0da2-11eb-8486-b65efb49c24d.png)


The infinite retries mean we can't leave the loop and recover the error manually.

**Comment by Xiralv** [comment]
Hi any updates on this? still replicating the issue in 4.1.6 thanks

**Comment by jzybert** [comment]
Seems to still be an issue in 4.1.8
